#pragma once
#ifndef __PLAYER_ANIMATION_STATE__
#define __PLAYER_ANIMATION_STATE__

enum PlayerAnimationState
{
	PLAYER_IDLE_RIGHT,
	PLAYER_IDLE_LEFT,
	PLAYER_RUN_RIGHT,
	PLAYER_RUN_LEFT,
	NOTHING,
	ATTACKING,
	SHOOTING,
	DEFENDING,
	EXPLODING,
	LEFTING,
	RIGHTING,
	JUMP_RIGHT,
	JUMP_LEFT,
	ROLL,
	DEAD,
	TOMB,
	NUM_OF_ANIMATION_STATES
};

#endif /* defined (__PLAYER_ANIMATION_STATE__)*/